### ISSUE TITLE
Enum/Scalar Handlers

### ISSUE THREAD

**Issue by xsc** [alumbra/alumbra#12]
We should introduce a way of coercing enum values and custom scalar types. Since `alumbra.spec` 0.1.6 every leaf value contains a type annotation which can be used for coercion.

`alumbra.claro` already implements coercion for the base scalar types, as well as translation for enums from/to kebab-case and snake_case respectively. All that remains to be done is offering a way to attach custom coercers.

**Comment by xsc** [comment]
As of alumbra/claro@65defb4, the `:scalars` key can be passed to the executor to define encode and decode functions for custom scalars or enums.

**Comment by willmruzek** [comment]
Is there any documentation to achieve a custom scalar? I'm trying to create a custom `Date` scalar.

**Comment by xsc** [comment]
@mruzekw I extended the docstring for [`alumbra.core/handler`](https://alumbra.github.io/alumbra/alumbra.core.html#var-handler) today, so there you should find some information. I'm still working on actual guides and examples.

In short:

```clojure
(alumbra.core/handler
  {:schema ...
   :query ...
   :scalars {"Date" {:encode format-date, :decode parse-date}})
```

__Edit:__ You'll also need to add the following line to your GraphQL schema:

```graphql
scalar Date
```

I hope this helps!
