### ISSUE TITLE
"me" query and sessions

### ISSUE THREAD

**Issue by willmruzek** [alumbra/alumbra#13]
I'd like to use some session data to resolve the "me" query. Though I'm unsure how to get the token and what not to the resolver. Could you help out?

Thanks!

**Comment by xsc** [comment]
@mruzekw You can pass a `:context` function to `alumbra.core/handler`. It expects an incoming Ring request and produces a map that is then automatically merged into the claro environment. Which should make it available to your resolvables.

```clojure
(require '[alumbra.core :as alumbra])

(defn- generate-context
  [{:keys [route-params headers]}]
  {:locale (:locale route-params)
   :token (read-token headers)})

(def graphql-handler
  (alumbra/handler
    {:schema  ...
     :query   QueryRoot
     :env     {:db ...}
     :context #'generate-context}))
```

Now, you should have access to the original `:env`, plus the generated context, e.g.:

```clojure
(defrecord Me []
  data/Resolvable
  (resolve! [_ {:keys [db token]}]
    (d/future
      (when token
        (when-let [id (token->person-id db token)]
          (->Person id))))))
```

Hope this helps!

**Comment by willmruzek** [comment]
That definitely helps. Thank you! 

Also, this is somewhat related question. I wondered how I could limit trips to the database. Say I was trying to query all users/persons: 

Assuming I had the following, how would I avoid a trip for each user (id)?

```
(defrecord User [id]
  data/Resolvable
  (resolve! [_ _]
    (db/get-user id))

(defrecord Users []
  data/Resolvable
  (resolve! [_ _]
    (->> (db/get-users)
         (map ->User))))
```

**Comment by xsc** [comment]
Check out the claro's [Batching](https://github.com/xsc/claro/blob/master/doc/00-basics.md#batching) documentation. Basically, you'll need to implement `BatchedResolvable`:

```clojure
(defrecord User [id]
  data/Resolvable
  data/BatchedResolvable
  (resolve-batch! [_ env a-batch-of-users]
    (d/future
      (->> (map :id a-batch-of-users)
           (db/get-users)
           ...))))
```

Note that `resolve-batch!` has to return either a seq of results matching the order of `a-batch-of-users` or a map associating every element from the batch with its result.

**Comment by willmruzek** [comment]
Cool, I'll check that out. Thanks again for your help!
