### ISSUE TITLE
Corner case with kebab-case conversion

### ISSUE THREAD

**Issue by caioaao** [alumbra/alumbra#22]
From [here](https://github.com/alumbra/alumbra.claro/blob/840383c0548587b9e69676f09d0fc9bccae45e7e/src/alumbra/claro/keys.clj#L4) (related to [this issue](https://github.com/qerub/camel-snake-kebab/issues/22)): when we declare a field with a word followed by a number, it gets converted with a dash between them. The problem is that, if the keyword comes without the dash, the framework breaks. For instance: we have `:column1` as a result from a query, but it's imposible to define it in graphql, as a field named `column1` will look for a key named `:column-1` from the resolvable.

**Comment by xsc** [comment]
@caioaao I don't think there can be general solution to this (since for someone else, `:column-1` might be just as reasonable a key). But alumbra supports a [`:wrap-key-fn`](https://github.com/alumbra/alumbra.claro/blob/master/src/alumbra/claro.clj#L121-L122) key that you can pass to `alumbra.core/handler` to process special keys:

```clojure
(alumbra.core/handler
  {...
   :wrap-key-fn
   (fn [wrap-fn] ;; this is alumbra.claro.keys/generate-key
     (fn [^String k]
       (if (.startsWith k "column")
         (keyword k)
         (wrap-fn k))))})
```

This way, you can completely switch out the translation logic of keys between GraphQL and Clojure, if you so desire. Hope that helps!

**Comment by caioaao** [comment]
thanks for the tip about `:wrap-key-fn`! that should do the trick for me.

Just a comment: I agree `:column-1` might be a reasonable result, but the problem I see is that the transformation is not symmetric, so `(-> "snake_case1" generate-key ->snake_case_string)` is not equal to `"snake_case1"`. but I understand that, as the code is also dealing with camel case, there is no general solution.

thanks again

**Comment by xsc** [comment]
> [...] the problem I see is that the transformation is not symmetric [...]

Yeah, that's not great in the general case. Note that in alumbra the transformation is only ever going in one direction, namely from the GraphQL name to the Clojure key.

I.e., when running a query we (basically) create a table that is then used to reverse map the result's Clojure keywords to the originally requested GraphQL names. So, symmetry is not a necessary property for us here.

I'll close this issue for now but feel free to comment or reopen if you encounter any new problems. :)
