### ISSUE TITLE
Q: parse (or convert to IDL) JSON schema representations

### ISSUE THREAD

**Issue by kipz** [alumbra/alumbra#25]
I'm looking at using alumbra to stitch together multiple GraphQL backends. 

Are there tools in alumbra that will allow me to convert the results of schema introspection from other backends in to IDL format, or otherwise parse them?

I'm happy to write a converter if one doesn't already exist.

**Comment by xsc** [comment]
As far as I understand your question, such functionality doesn't exist in alumbra.

But basically, what would need to happen is to transform the introspection result to conform to the `:alumbra/analyzed-schema` spec which can then be further used. Not sure how much effort this is though.

**Comment by kipz** [comment]
Thank you. I'll look in to it then.
